apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: mahdad1988/sleepr-notifications
          name: notifications
          env:
            - name: PORT
              value: '3005'
            - name: TCP_PORT
              value: '3006'
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: googleoauthclientid
                  key: clientId
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: googleoauthclientsecret
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: googleoauthrefreshtoken
                  key: refreshToken
            - name: SMTP_USER
              value: 'sleepr85@gmail.com'
          ports:
            - containerPort: 3005
            - containerPort: 3006
