apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
    - name: 'http'
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: 'tcp'
      port: 3006
      protocol: TCP
      targetPort: 3006
  selector:
    app: notifications
  type: ClusterIP

