services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: mahdad1988/sleepr-reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: mahdad1988/sleepr-auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
      - '3002:3002'
  payments:
    image: mahdad1988/sleepr-payments
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
      - '3004:3004'
  notifications:
    image: mahdad1988/sleepr-notifications
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3005:3005'
      - '3006:3006'
  mongo:
    image: mongo
